# User stats
GET localhost:3401/github/stats?query=darekkay

###

# Repository stats
GET localhost:3401/github/stats?query=darekkay/dashboard

###

# Missing query parameters
GET localhost:3401/github/stats

###
