# Random UUID
GET localhost:3401/passthrough?url=https://httpbin.org/uuid

###

# HTML response format
GET localhost:3401/passthrough?url=https://httpbin.org/html

###

# Missing query parameters
GET localhost:3401/passthrough

###
