/** AUTOGENERATED (yarn scan-widgets) **/
import { WidgetProperties, WidgetImports } from "widgets";

export type WidgetType =
  | "counter"
  | "cryptocurrencies"
  | "date-time"
  | "github-stats"
  | "image"
  | "qr-code"
  | "search"
  | "text"
  | "totd-chemical-elements"
  | "website";

const widgetProperties = {
  counter: {
    configurable: true,
    widgetType: "counter",
    category: "tracking",
    initialHeight: 2,
    initialWidth: 2,
    initialOptions: { headline: "" },
    initialMeta: {},
  },
  cryptocurrencies: {
    configurable: true,
    widgetType: "cryptocurrencies",
    category: "monitoring",
    initialHeight: 2,
    initialWidth: 3,
    initialOptions: { fiat: "eur", crypto: "bitcoin" },
    initialMeta: { updateCycle: { minutes: 15 }, updateStatus: "idle" },
  },
  "date-time": {
    configurable: false,
    widgetType: "date-time",
    category: "general",
    initialHeight: 2,
    initialWidth: 3,
    initialOptions: {},
    initialMeta: {},
  },
  "github-stats": {
    configurable: true,
    widgetType: "github-stats",
    category: "monitoring",
    initialHeight: 3,
    initialWidth: 3,
    initialOptions: {},
    initialMeta: {
      updateCycle: { hours: 24 },
      updateStatus: "idle",
      headlineIcon: "github",
    },
  },
  image: {
    configurable: true,
    widgetType: "image",
    category: "media",
    initialHeight: 4,
    initialWidth: 4,
    initialOptions: { url: "" },
    initialMeta: {},
  },
  "qr-code": {
    configurable: true,
    widgetType: "qr-code",
    category: "tools",
    initialHeight: 2,
    initialWidth: 2,
    initialOptions: { headline: "", content: "" },
    initialMeta: {},
  },
  search: {
    configurable: true,
    widgetType: "search",
    category: "tools",
    initialHeight: 2,
    initialWidth: 4,
    initialOptions: {
      title: "DuckDuckGo",
      pattern: "https://duckduckgo.com/?q=%s",
    },
    initialMeta: {},
  },
  text: {
    configurable: false,
    widgetType: "text",
    category: "general",
    initialHeight: 4,
    initialWidth: 4,
    initialOptions: {},
    initialMeta: {},
  },
  "totd-chemical-elements": {
    configurable: false,
    widgetType: "totd-chemical-elements",
    category: "knowledge",
    initialHeight: 2,
    initialWidth: 2,
    initialOptions: {},
    initialMeta: { updateCycle: { hours: 24 }, updateStatus: "idle" },
  },
  website: {
    configurable: true,
    widgetType: "website",
    category: "media",
    initialHeight: 5,
    initialWidth: 5,
    initialOptions: { url: "" },
    initialMeta: {},
  },
} as Record<WidgetType, WidgetProperties>;
export default widgetProperties;

export const widgetImports = {
  counter: {
    component: async () => import("widgets/counter"),
    configuration: async () => import("widgets/counter/configuration"),
  },
  cryptocurrencies: {
    component: async () => import("widgets/cryptocurrencies"),
    configuration: async () => import("widgets/cryptocurrencies/configuration"),
  },
  "date-time": {
    component: async () => import("widgets/date-time"),
  },
  "github-stats": {
    component: async () => import("widgets/github-stats"),
    configuration: async () => import("widgets/github-stats/configuration"),
  },
  image: {
    component: async () => import("widgets/image"),
    configuration: async () => import("widgets/image/configuration"),
  },
  "qr-code": {
    component: async () => import("widgets/qr-code"),
    configuration: async () => import("widgets/qr-code/configuration"),
  },
  search: {
    component: async () => import("widgets/search"),
    configuration: async () => import("widgets/search/configuration"),
  },
  text: {
    component: async () => import("widgets/text"),
  },
  "totd-chemical-elements": {
    component: async () => import("widgets/totd-chemical-elements"),
  },
  website: {
    component: async () => import("widgets/website"),
    configuration: async () => import("widgets/website/configuration"),
  },
} as Record<WidgetType, WidgetImports>;

export const initialMeta = (widgetType: WidgetType) =>
  widgetProperties[widgetType].initialMeta;
