/** AUTOGENERATED (yarn scan-widgets) **/

const widgets = {
  counter: {},
  cryptocurrencies: { updateCycle: { minutes: 15 } },
  "date-time": {},
  "github-stats": { updateCycle: { hours: 24 } },
  image: {},
  "qr-code": {},
  search: {},
  text: {},
  "totd-chemical-elements": { updateCycle: { hours: 24 } },
  website: {},
} as Record<string, any>;
export default widgets;
