/** AUTOGENERATED (yarn scan:widgets) **/

const widgets: Record<string, any> = {
  chart: { updateCycle: { hours: 24 } },
  counter: {},
  cryptocurrencies: { updateCycle: { minutes: 15 } },
  "date-time": {},
  "github-stats": { updateCycle: { hours: 24 } },
  image: {},
  "qr-code": {},
  "random-image": { updateCycle: { hours: 24 } },
  search: {},
  text: {},
  "totd-chemical-elements": { updateCycle: { hours: 24 } },
  "totd-world-countries": { updateCycle: { hours: 24 } },
  "twitter-stats": { updateCycle: { hours: 24 } },
  weather: { updateCycle: { hours: 4 } },
  website: {},
  "youtube-stats": { updateCycle: { hours: 24 } },
};
export default widgets;
