/** AUTOGENERATED (yarn scan-widgets) **/
import { WidgetProperties } from "./index";

export default {
  "date-time": {
    configurable: false,
    widgetType: "date-time",
    initialHeight: 1,
    initialWidth: 2,
    initialOptions: {},
    initialMeta: {}
  },
  website: {
    configurable: true,
    widgetType: "website",
    initialHeight: 3,
    initialWidth: 2,
    initialOptions: {},
    initialMeta: {}
  },
  image: {
    configurable: true,
    widgetType: "image",
    initialHeight: 3,
    initialWidth: 2,
    initialOptions: {},
    initialMeta: {}
  },
  search: {
    configurable: true,
    widgetType: "search",
    initialHeight: 1,
    initialWidth: 2,
    initialOptions: {
      title: "DuckDuckGo",
      pattern: "https://duckduckgo.com/?q=%s"
    },
    initialMeta: {}
  },
  text: {
    configurable: false,
    widgetType: "text",
    initialHeight: 2,
    initialWidth: 2,
    initialOptions: {},
    initialMeta: {}
  },
  "totd-chemical-elements": {
    configurable: false,
    widgetType: "totd-chemical-elements",
    initialHeight: 1,
    initialWidth: 1,
    initialOptions: {},
    initialMeta: { updateCycle: { hours: 24 } }
  }
} as { [key: string]: WidgetProperties };
