name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  # app module
  app:
    runs-on: ubuntu-latest
    name: app-node-${{ matrix.node }}
    strategy:
      matrix:
        node: [ 16, 20 ]
      fail-fast: true
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "app"

      - name: Install dependencies
        run: yarn install --pure-lockfile --prefer-offline

      - name: Validate
        run: yarn ci

      - name: Build
        run: yarn build

  # server module
  server:
    runs-on: ubuntu-latest
    name: server-node-${{ matrix.node }}
    strategy:
      matrix:
        node: [ 16, 20 ]
      fail-fast: true
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "server"

      - name: Install dependencies
        run: yarn install --pure-lockfile --prefer-offline

      - name: Validate
        run: yarn ci

  # docs module
  docs:
    runs-on: ubuntu-latest
    name: docs-node-${{ matrix.node }}
    strategy:
      matrix:
        node: [ 16 ]
      fail-fast: true
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "docs"

      - name: Install dependencies
        run: yarn install --pure-lockfile --prefer-offline

      - name: Build
        run: yarn build
